# Generated by Django 5.2.1 on 2025-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bockmarked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
